name: DevSecOps Workflow

on:
  push:
    branches:
      - main


jobs:
  code-scan:
    name: Code Scan with Snyk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.1'
    - name: Code Scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=critical

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: code-scan
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yusragokce/devops-with-github-actions:latest

  image-scan:
    name: Scan the Docker image with Snyk
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
    - name: Scan the Docker image with Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: yusragokce/devops-with-github-actions:latest
        command: test
        args: --severity-threshold=critical